---
sidebar: sidebar 
permalink: beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Per impostare un nodo di controllo Ansible, identificare una macchina virtuale o fisica con accesso di rete alle porte di gestione di tutti i nodi di file e blocchi che possono essere utilizzati per configurare la soluzione. 
---
= Impostare un nodo di controllo Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per impostare un nodo di controllo Ansible, è necessario identificare una macchina virtuale o fisica con accesso di rete alle porte di gestione di tutti i nodi di file e blocchi che possono essere utilizzati per configurare la soluzione.

I seguenti passaggi sono stati testati su CentOS 8.4. Per i passaggi specifici della distribuzione Linux preferita, consultare la https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Documentazione Ansible"^].

. Installare Python 3.9 e assicurarsi che la versione corretta di `pip` è installato.
+
....
sudo dnf install python3.9 -y
sudo dnf install python39-pip
sudo dnf install sshpass
....
. Creare collegamenti simbolici, assicurandosi che il binario Python 3.9 venga utilizzato ogni volta `python3` oppure `python` viene chiamato.
+
....
sudo ln -sf /usr/bin/python3.9 /usr/bin/python3
sudo ln -sf /usr/bin/python3 /usr/bin/python
....
. Installare i pacchetti Python richiesti dalle raccolte NetApp BeeGFS.
+
....
python3 -m pip install ansible cryptography netaddr
....
+

NOTE: Per assicurarsi di installare una versione supportata di Ansible e tutti i pacchetti Python richiesti, fare riferimento al file Readme della raccolta BeeGFS. Le versioni supportate sono indicate anche nella link:beegfs-technology-requirements.html["Requisiti tecnici"].

. Verificare che siano installate le versioni corrette di Ansible e Python.
+
....
ansible --version
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Mar 10 2021, 17:29:56) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True
....
. Memorizzare gli inventari Ansible utilizzati per descrivere l'implementazione di BeeGFS nei sistemi di controllo del codice sorgente come Git o BitBucket, quindi installare Git per interagire con tali sistemi.
+
....
sudo dnf install git -y
....
. Impostare SSH senza password. Questo è il modo più semplice per consentire ad Ansible di accedere ai nodi di file BeeGFS remoti dal nodo di controllo Ansible.
+
.. Nel nodo di controllo Ansible, se necessario, generare una coppia di chiavi pubbliche utilizzando `ssh-keygen`
.. Impostare SSH senza password su ciascuno dei nodi di file utilizzando `ssh-copy-id <ip_or_hostname>`
+
Non impostare * SSH senza password sui nodi di blocco. Questo non è supportato né richiesto.



. Utilizzare Ansible Galaxy per installare la versione della raccolta BeeGFS elencata nella link:beegfs-technology-requirements.html["Requisiti tecnici"].
+
Questa installazione include dipendenze Ansible aggiuntive, come il software NetApp SANtricity e le raccolte host.

+
....
ansible-galaxy collection install netapp_eseries.beegfs:==3.0.1
....

