---
sidebar: sidebar 
permalink: beegfs-deploy-define-inventory.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Dopo aver definito la struttura generale di inventario Ansible, definire la configurazione per ciascun building block nel file system BeeGFS. 
---
= Definire l'inventario Ansible per gli elementi di base BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver definito la struttura generale di inventario Ansible, definire la configurazione per ciascun building block nel file system BeeGFS.

Queste istruzioni di implementazione mostrano come implementare un file system costituito da un building block di base che include servizi di gestione, metadati e storage, un secondo building block con metadati e servizi di storage e un terzo building block di solo storage.

Questi passaggi hanno lo scopo di mostrare l'intera gamma di profili di configurazione tipici che è possibile utilizzare per configurare gli elementi di base di NetApp BeeGFS in modo da soddisfare i requisiti del file system generale BeeGFS.


NOTE: In questa e nelle sezioni successive, modificare in base alle necessità per creare l'inventario che rappresenta il file system BeeGFS che si desidera implementare. In particolare, utilizzare i nomi host Ansible che rappresentano ciascun nodo di file o blocco e lo schema di indirizzamento IP desiderato per la rete di storage per garantire che possa scalare in base al numero di nodi di file e client BeeGFS.



== Fase 1: Creare il file di inventario Ansible

.Fasi
. Creare un nuovo `inventory.yml` quindi inserire i seguenti parametri, sostituendo gli host in `eseries_storage_systems` in base alle necessità per rappresentare i nodi a blocchi nell'implementazione. I nomi devono corrispondere al nome utilizzato per `host_vars/<FILENAME>.yml`.
+
....
# BeeGFS HA (High Availability) cluster inventory.
all:
  children:
    # Ansible group representing all block nodes:
    eseries_storage_systems:
      hosts:
        ictad22a01:
        ictad22a02:
        ictad22a03:
        ictad22a04:
        ictad22a05:
        ictad22a06:
    # Ansible group representing all file nodes:
    ha_cluster:
      children:
....
+
Nelle sezioni successive, verranno creati ulteriori gruppi Ansible in `ha_cluster` Che rappresentano i servizi BeeGFS che si desidera eseguire nel cluster.





== Fase 2: Configurare l'inventario per un building block di gestione, metadati e storage

Il primo building block nel cluster o nel building block di base deve includere il servizio di gestione BeeGFS insieme ai metadati e ai servizi di storage:

.Fasi
. Poll `inventory.yml`, compilare i seguenti parametri in `ha_cluster: children`:
+
....
      # ictad22h01/ictad22h02 HA Pair (mgmt/meta/storage building block):
        mgmt:
          hosts:
            ictad22h01:
            ictad22h02:
        meta_01:
          hosts:
            ictad22h01:
            ictad22h02:
        stor_01:
          hosts:
            ictad22h01:
            ictad22h02:
        meta_02:
          hosts:
            ictad22h01:
            ictad22h02:
        stor_02:
          hosts:
            ictad22h01:
            ictad22h02:
        meta_03:
          hosts:
            ictad22h01:
            ictad22h02:
        stor_03:
          hosts:
            ictad22h01:
            ictad22h02:
        meta_04:
          hosts:
            ictad22h01:
            ictad22h02:
        stor_04:
          hosts:
            ictad22h01:
            ictad22h02:
        meta_05:
          hosts:
            ictad22h02:
            ictad22h01:
        stor_05:
          hosts:
            ictad22h02:
            ictad22h01:
        meta_06:
          hosts:
            ictad22h02:
            ictad22h01:
        stor_06:
          hosts:
            ictad22h02:
            ictad22h01:
        meta_07:
          hosts:
            ictad22h02:
            ictad22h01:
        stor_07:
          hosts:
            ictad22h02:
            ictad22h01:
        meta_08:
          hosts:
            ictad22h02:
            ictad22h01:
        stor_08:
          hosts:
            ictad22h02:
            ictad22h01:
....
. Creare il file `group_vars/mgmt.yml` e includere quanto segue:
+
....
# mgmt - BeeGFS HA Management Resource Group
# OPTIONAL: Override default BeeGFS management configuration:
# beegfs_ha_beegfs_mgmtd_conf_resource_group_options:
#  <beegfs-mgmt.conf:key>:<beegfs-mgmt.conf:value>
floating_ips:
  - i1b: 100.127.101.0/16
  - i2b: 100.128.102.0/16
beegfs_service: management
beegfs_targets:
  ictad22a01:
    eseries_storage_pool_configuration:
      - name: beegfs_m1_m2_m5_m6
        raid_level: raid1
        criteria_drive_count: 4
        common_volume_configuration:
          segment_size_kb:  128
        volumes:
          - size: 1
            owning_controller: A
....
. Sotto `group_vars/`, creare i file per i gruppi di risorse `meta_01` attraverso `meta_08` utilizzando il seguente modello, inserire i valori segnaposto per ogni servizio che fa riferimento alla tabella seguente:
+
....
# meta_0X - BeeGFS HA Metadata Resource Group
beegfs_ha_beegfs_meta_conf_resource_group_options:
  connMetaPortTCP: <PORT>
  connMetaPortUDP: <PORT>
  tuneBindToNumaZone: <NUMA ZONE>
floating_ips:
  - <PREFERRED PORT:IP/SUBNET> # Example: i1b:192.168.120.1/16
  - <SECONDARY PORT:IP/SUBNET>
beegfs_service: metadata
beegfs_targets:
  <BLOCK NODE>:
    eseries_storage_pool_configuration:
      - name: <STORAGE POOL>
        raid_level: raid1
        criteria_drive_count: 4
        common_volume_configuration:
          segment_size_kb:  128
        volumes:
          - size: 21.25 # SEE NOTE BELOW!
            owning_controller: <OWNING CONTROLLER>
....
+

NOTE: Le dimensioni del volume vengono specificate come percentuale del pool di storage complessivo (definito anche gruppo di volumi). NetApp consiglia vivamente di lasciare una certa capacità libera in ogni pool per consentire lo spazio necessario per l'overprovisioning SSD (per ulteriori informazioni, vedere https://www.netapp.com/pdf.html?item=/media/17009-tr4800pdf.pdf["Introduzione all'array NetApp EF600"^]). Il pool di storage, `beegfs_m1_m2_m5_m6`, alloca inoltre l'1% della capacità del pool per il servizio di gestione. Pertanto, per i volumi di metadati nel pool di storage, `beegfs_m1_m2_m5_m6`, Se si utilizzano dischi da 1,92 TB o 3,84 TB, impostare questo valore su `21.25`; Per dischi da 7,65 TB, impostare questo valore su `22.25`; E per i dischi da 15,3 TB, impostare questo valore su `23.75`.

+
|===
| Nome del file | Porta | IP mobili | Zona NUMA | Nodo del blocco | Pool di storage | Controller proprietario 


| meta_01.yml | 8015 | i1b:100.127.101.1/16 i2b:100.128.102.1/16 | 0 | ictad22a01 | beegfs_m1_m2_m5_m6 | R 


| meta_02.yml | 8025 | i2b:100.128.102.2/16 i1b:100.127.101.2/16 | 0 | ictad22a01 | beegfs_m1_m2_m5_m6 | B 


| meta_03.yml | 8035 | i3b:100.127.101.3/16 i4b:100.128.102.3/16 | 1 | ictad22a02 | beegfs_m3_m4_m7_m8 | R 


| meta_04.yml | 8045 | i4b:100.128.102.4/16 i3b:100.127.101.4/16 | 1 | ictad22a02 | beegfs_m3_m4_m7_m8 | B 


| meta_05.yml | 8055 | i1b:100.127.101.5/16 i2b:100.128.102.5/16 | 0 | ictad22a01 | beegfs_m1_m2_m5_m6 | R 


| meta_06.yml | 8065 | i2b:100.128.102.6/16 i1b:100.127.101.6/16 | 0 | ictad22a01 | beegfs_m1_m2_m5_m6 | B 


| meta_07.yml | 8075 | i3b:100.127.101.7/16 i4b:100.128.102.7/16 | 1 | ictad22a02 | beegfs_m3_m4_m7_m8 | R 


| meta_08.yml | 8085 | i4b:100.128.102.8/16 i3b:100.127.101.8/16 | 1 | ictad22a02 | beegfs_m3_m4_m7_m8 | B 
|===
. Sotto `group_vars/`, creare i file per i gruppi di risorse `stor_01` attraverso `stor_08` utilizzando il seguente modello, inserire i valori segnaposto per ciascun servizio che fa riferimento all'esempio:
+
....
# stor_0X - BeeGFS HA Storage Resource Groupbeegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: <PORT>
  connStoragePortUDP: <PORT>
  tuneBindToNumaZone: <NUMA ZONE>
floating_ips:
  - <PREFERRED PORT:IP/SUBNET>
  - <SECONDARY PORT:IP/SUBNET>
beegfs_service: storage
beegfs_targets:
  <BLOCK NODE>:
    eseries_storage_pool_configuration:
      - name: <STORAGE POOL>
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512        volumes:
          - size: 21.50 # See note below!             owning_controller: <OWNING CONTROLLER>
          - size: 21.50            owning_controller: <OWNING CONTROLLER>
....
+

NOTE: Per le dimensioni corrette da utilizzare, vedere link:beegfs-deploy-recommended-volume-percentages.html["Percentuali consigliate di overprovisioning del pool di storage"].

+
|===
| Nome del file | Porta | IP mobili | Zona NUMA | Nodo del blocco | Pool di storage | Controller proprietario 


| stor_01.yml | 8013 | i1b:100.127.103.1/16 i2b:100.128.104.1/16 | 0 | ictad22a01 | beegfs_s1_s2 | R 


| stor_02.yml | 8023 | i2b:100.128.104.2/16 i1b:100.127.103.2/16 | 0 | ictad22a01 | beegfs_s1_s2 | B 


| stor_03.yml | 8033 | i3b:100.127.103.3/16 i4b:100.128.104.3/16 | 1 | ictad22a02 | beegfs_s3_s4 | R 


| stor_04.yml | 8043 | i4b:100.128.104.4/16 i3b:100.127.103.4/16 | 1 | ictad22a02 | beegfs_s3_s4 | B 


| stor_05.yml | 8053 | i1b:100.127.103.5/16 i2b:100.128.104.5/16 | 0 | ictad22a01 | beegfs_s5_s6 | R 


| stor_06.yml | 8063 | i2b:100.128.104.6/16 i1b:100.127.103.6/16 | 0 | ictad22a01 | beegfs_s5_s6 | B 


| stor_07.yml | 8073 | i3b:100.127.103.7/16 i4b:100.128.104.7/16 | 1 | ictad22a02 | beegfs_s7_s8 | R 


| stor_08.yml | 8083 | i4b:100.128.104.8/16 i3b:100.127.103.8/16 | 1 | ictad22a02 | beegfs_s7_s8 | B 
|===




== Fase 3: Configurare l'inventario per un building block di metadati + storage

Questi passaggi descrivono come configurare un inventario Ansible per un building block di storage + metadati BeeGFS.

.Fasi
. Poll `inventory.yml`, inserire i seguenti parametri nella configurazione esistente:
+
....
        meta_09:
          hosts:
            ictad22h03:
            ictad22h04:
        stor_09:
          hosts:
            ictad22h03:
            ictad22h04:
        meta_10:
          hosts:
            ictad22h03:
            ictad22h04:
        stor_10:
          hosts:
            ictad22h03:
            ictad22h04:
        meta_11:
          hosts:
            ictad22h03:
            ictad22h04:
        stor_11:
          hosts:
            ictad22h03:
            ictad22h04:
        meta_12:
          hosts:
            ictad22h03:
            ictad22h04:
        stor_12:
          hosts:
            ictad22h03:
            ictad22h04:
        meta_13:
          hosts:
            ictad22h04:
            ictad22h03:
        stor_13:
          hosts:
            ictad22h04:
            ictad22h03:
        meta_14:
          hosts:
            ictad22h04:
            ictad22h03:
        stor_14:
          hosts:
            ictad22h04:
            ictad22h03:
        meta_15:
          hosts:
            ictad22h04:
            ictad22h03:
        stor_15:
          hosts:
            ictad22h04:
            ictad22h03:
        meta_16:
          hosts:
            ictad22h04:
            ictad22h03:
        stor_16:
          hosts:
            ictad22h04:
            ictad22h03:
....
. Sotto `group_vars/`, creare i file per i gruppi di risorse `meta_09` attraverso `meta_16` utilizzando il seguente modello, inserire i valori segnaposto per ciascun servizio che fa riferimento all'esempio:
+
....
# meta_0X - BeeGFS HA Metadata Resource Group
beegfs_ha_beegfs_meta_conf_resource_group_options:
  connMetaPortTCP: <PORT>
  connMetaPortUDP: <PORT>
  tuneBindToNumaZone: <NUMA ZONE>
floating_ips:
  - <PREFERRED PORT:IP/SUBNET>
  - <SECONDARY PORT:IP/SUBNET>
beegfs_service: metadata
beegfs_targets:
  <BLOCK NODE>:
    eseries_storage_pool_configuration:
      - name: <STORAGE POOL>
        raid_level: raid1
        criteria_drive_count: 4
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: 21.5 # SEE NOTE BELOW!
            owning_controller: <OWNING CONTROLLER>
....
+

NOTE: Per le dimensioni corrette da utilizzare, vedere link:beegfs-deploy-recommended-volume-percentages.html["Percentuali consigliate di overprovisioning del pool di storage"].

+
|===
| Nome del file | Porta | IP mobili | Zona NUMA | Nodo del blocco | Pool di storage | Controller proprietario 


| meta_09.yml | 8015 | i1b:100.127.101.9/16 i2b:100.128.102.9/16 | 0 | ictad22a03 | beegfs_m9_m10_m13_m14 | R 


| meta_10.yml | 8025 | i2b:100.128.102.10/16 i1b:100.127.101.10/16 | 0 | ictad22a03 | beegfs_m9_m10_m13_m14 | B 


| meta_11.yml | 8035 | i3b:100.127.101.11/16 i4b:100.128.102.11/16 | 1 | ictad22a04 | beegfs_m11_m12_m15_m16 | R 


| meta_12.yml | 8045 | i4b:100.128.102.12/16 i3b:100.127.101.12/16 | 1 | ictad22a04 | beegfs_m11_m12_m15_m16 | B 


| meta_13.yml | 8055 | i1b:100.127.101.13/16 i2b:100.128.102.13/16 | 0 | ictad22a03 | beegfs_m9_m10_m13_m14 | R 


| meta_14.yml | 8065 | i2b:100.128.102.14/16 i1b:100.127.101.14/16 | 0 | ictad22a03 | beegfs_m9_m10_m13_m14 | B 


| meta_15.yml | 8075 | i3b:100.127.101.15/16 i4b:100.128.102.15/16 | 1 | ictad22a04 | beegfs_m11_m12_m15_m16 | R 


| meta_16.yml | 8085 | i4b:100.128.102.16/16 i3b:100.127.101.16/16 | 1 | ictad22a04 | beegfs_m11_m12_m15_m16 | B 
|===
. Sotto `group_vars/,` creare file per gruppi di risorse `stor_09` attraverso `stor_16` utilizzando il seguente modello, inserire i valori segnaposto per ciascun servizio che fa riferimento all'esempio:
+
....
# stor_0X - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: <PORT>
  connStoragePortUDP: <PORT>
  tuneBindToNumaZone: <NUMA ZONE>
floating_ips:
  - <PREFERRED PORT:IP/SUBNET>
  - <SECONDARY PORT:IP/SUBNET>
beegfs_service: storage
beegfs_targets:
  <BLOCK NODE>:
    eseries_storage_pool_configuration:
      - name: <STORAGE POOL>
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512        volumes:
          - size: 21.50 # See note below!
            owning_controller: <OWNING CONTROLLER>
          - size: 21.50            owning_controller: <OWNING CONTROLLER>
....
+

NOTE: Per le dimensioni corrette da utilizzare, vedere link:beegfs-deploy-recommended-volume-percentages.html["Percentuali consigliate di overprovisioning del pool di storage"]..

+
|===
| Nome del file | Porta | IP mobili | Zona NUMA | Nodo del blocco | Pool di storage | Controller proprietario 


| stor_09.yml | 8013 | i1b:100.127.103.9/16 i2b:100.128.104.9/16 | 0 | ictad22a03 | beegfs_s9_s10 | R 


| stor_10.yml | 8023 | i2b:100.128.104.10/16 i1b:100.127.103.10/16 | 0 | ictad22a03 | beegfs_s9_s10 | B 


| stor_11.yml | 8033 | i3b:100.127.103.11/16 i4b:100.128.104.11/16 | 1 | ictad22a04 | beegfs_s11_s12 | R 


| stor_12.yml | 8043 | i4b:100.128.104.12/16 i3b:100.127.103.12/16 | 1 | ictad22a04 | beegfs_s11_s12 | B 


| stor_13.yml | 8053 | i1b:100.127.103.13/16 i2b:100.128.104.13/16 | 0 | ictad22a03 | beegfs_s13_s14 | R 


| stor_14.yml | 8063 | i2b:100.128.104.14/16 i1b:100.127.103.14/16 | 0 | ictad22a03 | beegfs_s13_s14 | B 


| stor_15.yml | 8073 | i3b:100.127.103.15/16 i4b:100.128.104.15/16 | 1 | ictad22a04 | beegfs_s15_s16 | R 


| stor_16.yml | 8083 | i4b:100.128.104.16/16 i3b:100.127.103.16/16 | 1 | ictad22a04 | beegfs_s15_s16 | B 
|===




== Fase 4: Configurare l'inventario per un building block di solo storage

Questi passaggi descrivono come configurare un inventario Ansible per un building block BeeGFS solo storage. La differenza principale tra l'impostazione della configurazione per un metadata + storage rispetto a un building block solo storage è l'omissione di tutti i gruppi di risorse di metadati e la modifica `criteria_drive_count` da 10 a 12 per ogni pool di storage.

.Fasi
. Poll `inventory.yml`, inserire i seguenti parametri nella configurazione esistente:
+
....
      # ictad22h05/ictad22h06 HA Pair (storage only building block):
        stor_17:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_18:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_19:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_20:
          hosts:
            ictad22h05:
            ictad22h06:
        stor_21:
          hosts:
            ictad22h06:
            ictad22h05:
        stor_22:
          hosts:
            ictad22h06:
            ictad22h05:
        stor_23:
          hosts:
            ictad22h06:
            ictad22h05:
        stor_24:
          hosts:
            ictad22h06:
            ictad22h05:
....
. Sotto `group_vars/`, creare i file per i gruppi di risorse `stor_17` attraverso `stor_24` utilizzando il seguente modello, inserire i valori segnaposto per ciascun servizio che fa riferimento all'esempio:
+
....
# stor_0X - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: <PORT>
  connStoragePortUDP: <PORT>
  tuneBindToNumaZone: <NUMA ZONE>
floating_ips:
  - <PREFERRED PORT:IP/SUBNET>
  - <SECONDARY PORT:IP/SUBNET>
beegfs_service: storage
beegfs_targets:
  <BLOCK NODE>:
    eseries_storage_pool_configuration:
      - name: <STORAGE POOL>
        raid_level: raid6
        criteria_drive_count: 12
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: 21.50 # See note below!
            owning_controller: <OWNING CONTROLLER>
          - size: 21.50
            owning_controller: <OWNING CONTROLLER>
....
+

NOTE: Per le dimensioni corrette da utilizzare, vedere link:beegfs-deploy-recommended-volume-percentages.html["Percentuali consigliate di overprovisioning del pool di storage"].

+
|===
| Nome del file | Porta | IP mobili | Zona NUMA | Nodo del blocco | Pool di storage | Controller proprietario 


| stor_17.yml | 8013 | i1b:100.127.103.17/16 i2b:100.128.104.17/16 | 0 | ictad22a05 | beegfs_s17_s18 | R 


| stor_18.yml | 8023 | i2b:100.128.104.18/16 i1b:100.127.103.18/16 | 0 | ictad22a05 | beegfs_s17_s18 | B 


| stor_19.yml | 8033 | i3b:100.127.103.19/16 i4b:100.128.104.19/16 | 1 | ictad22a06 | beegfs_s19_s20 | R 


| stor_20.yml | 8043 | i4b:100.128.104.20/16 i3b:100.127.103.20/16 | 1 | ictad22a06 | beegfs_s19_s20 | B 


| stor_21.yml | 8053 | i1b:100.127.103.21/16 i2b:100.128.104.21/16 | 0 | ictad22a05 | beegfs_s21_s22 | R 


| stor_22.yml | 8063 | i2b:100.128.104.22/16 i1b:100.127.103.22/16 | 0 | ictad22a05 | beegfs_s21_s22 | B 


| stor_23.yml | 8073 | i3b:100.127.103.23/16 i4b:100.128.104.23/16 | 1 | ictad22a06 | beegfs_s23_s24 | R 


| stor_24.yml | 8083 | i4b:100.128.104.24/16 i3b:100.127.103.24/16 | 1 | ictad22a06 | beegfs_s23_s24 | B 
|===

