---
sidebar: sidebar 
permalink: beegfs-solution-overview.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: 'La soluzione BeeGFS su NetApp combina il file system parallelo BeeGFS con i sistemi storage NetApp EF600 per un"infrastruttura affidabile, scalabile e conveniente che tiene il passo con i carichi di lavoro esigenti.' 
---
= Panoramica della soluzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La soluzione BeeGFS su NetApp combina il file system parallelo BeeGFS con i sistemi storage NetApp EF600 per un'infrastruttura affidabile, scalabile e conveniente che tiene il passo con i carichi di lavoro esigenti.



== Programma NVA

La soluzione BeeGFS su NetApp fa parte del programma NetApp Verified Architecture (NVA), che offre ai clienti configurazioni di riferimento e indicazioni sul dimensionamento per carichi di lavoro e casi di utilizzo specifici. Le soluzioni NVA sono testate e progettate per ridurre al minimo i rischi di implementazione e accelerare il time-to-market.



== Panoramica del progetto

La soluzione BeeGFS su NetApp è progettata come un'architettura a building block scalabile, configurabile per una vasta gamma di carichi di lavoro esigenti. Che si tratti di molti file di piccole dimensioni, della gestione di operazioni sostanziali di file di grandi dimensioni o di un carico di lavoro ibrido, il file system può essere personalizzato in base a tali esigenze. L'alta disponibilità è integrata nel progetto con l'utilizzo di una struttura hardware a due livelli che consente il failover indipendente a più livelli hardware e garantisce prestazioni costanti, anche durante il degrado parziale del sistema. Il file system BeeGFS consente di creare un ambiente scalabile e ad alte prestazioni in diverse distribuzioni Linux e presenta ai client un unico spazio dei nomi di storage facilmente accessibile. Per ulteriori informazioni, vedere link:beegfs-architecture-overview.html["panoramica dell'architettura"].



== Casi di utilizzo

I seguenti casi di utilizzo si applicano alla soluzione BeeGFS su NetApp:

* Sistemi NVIDIA DGX SuperPOD dotati di DGX con GPU A100, H100, H200 e B200.
* Intelligenza artificiale (ai), tra cui apprendimento automatico (ML), apprendimento approfondito (DL), elaborazione del linguaggio naturale (NLP) su larga scala e comprensione del linguaggio naturale (NLU). Per ulteriori informazioni, vedere https://www.netapp.com/blog/beefs-for-ai-fact-vs-fiction/["BeeGFS per l'ai: Fatti e finzione"^].
* High-performance computing (HPC) che include applicazioni accelerate da MPI (message passing interface) e altre tecniche di calcolo distribuito. Per ulteriori informazioni, vedere https://www.netapp.com/blog/beegfs-for-ai-ml-dl/["Perché BeeGFS va oltre l'HPC"^].
* Carichi di lavoro delle applicazioni caratterizzati da:
+
** Lettura o scrittura su file di dimensioni superiori a 1 GB
** Lettura o scrittura sullo stesso file da parte di più client (10, 100 e 1000)


* Set di dati multi-terabyte o multi-petabyte.
* Ambienti che richiedono un singolo spazio dei nomi dello storage, ottimizzabili per una combinazione di file di grandi e piccoli dimensioni.




== Benefici

I vantaggi principali dell'utilizzo di BeeGFS su NetApp includono:

* Disponibilità di progetti hardware verificati che forniscono la completa integrazione di componenti hardware e software per garantire performance e affidabilità prevedibili.
* Implementazione e gestione con Ansible per semplicità e coerenza su larga scala.
* Monitoraggio e osservabilità forniti con e-Series Performance Analyzer e plug-in BeeGFS. Per ulteriori informazioni, vedere https://www.netapp.com/blog/monitoring-netapp-eseries/["Presentazione di un framework per il monitoraggio delle soluzioni NetApp e-Series"^].
* Alta disponibilità con un'architettura a disco condiviso che garantisce la durata e la disponibilità dei dati.
* Supporto per la moderna gestione e orchestrazione dei workload con container e Kubernetes. Per ulteriori informazioni, vedere https://www.netapp.com/blog/kubernetes-meet-beegfs/["Kubernetes incontra BeeGFS: Una storia di investimenti a prova di futuro"^].

