---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Per impostare un nodo di controllo Ansible, identificare una macchina virtuale o fisica con accesso di rete alle porte di gestione di tutti i nodi di file e blocchi che possono essere utilizzati per configurare la soluzione. 
---
= Impostare un nodo di controllo Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per configurare un nodo di controllo Ansible, è necessario designare una macchina virtuale o fisica con accesso alla rete a tutti i nodi di file e blocchi implementati per la soluzione BeeGFS su NetApp.

Per un elenco delle versioni dei pacchetti consigliate, consultare lalink:beegfs-technology-requirements.html#ansible-control-node-requirements["Requisiti tecnici"]. I seguenti passaggi sono stati testati su Ubuntu 22,04. Per i passaggi specifici della distribuzione Linux preferita, vedere https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Documentazione Ansible"^].

. Dal nodo di controllo Ansible, installare i seguenti pacchetti Python e Python Virtual Environment.
+
[source, console]
----
sudo apt-get install python3 python3-pip python3-setuptools python3.10-venv
----
. Creare un ambiente virtuale Python
+
[source, console]
----
python3 -m venv ~/pyenv
----
. Attivare l'ambiente virtuale.
+
[source, console]
----
source ~/pyenv/bin/activate
----
. Installare i pacchetti Python richiesti nell'ambiente virtuale attivato.
+
[source, console]
----
pip install ansible netaddr cryptography passlib
----
. Installare la raccolta BeeGFS utilizzando Ansible Galaxy.
+
[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs
----
. Verificare che le versioni installate di Ansible, Python e della raccolta BeeGFS corrispondano a link:beegfs-technology-requirements.html#ansible-control-node-requirements["Requisiti tecnici"].
+
[source, console]
----
ansible --version
ansible-galaxy collection list netapp_eseries.beegfs
----
. Configurare SSH senza password per consentire a Ansible di accedere ai nodi di file BeeGFS remoti dal nodo di controllo Ansible.
+
.. Sul nodo di controllo Ansible, se necessario, generare una coppia di chiavi pubbliche.
+
[source, console]
----
ssh-keygen
----
.. Impostare SSH senza password per ciascuno dei nodi di file.
+
[source, console]
----
ssh-copy-id <ip_or_hostname>
----





IMPORTANT: Non impostare * SSH senza password sui nodi di blocco. Questo non è supportato né richiesto.
