---
sidebar: sidebar 
permalink: second-gen/beegfs-gens.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: La soluzione BeeGFS su NetApp si trova attualmente nella sua seconda progettazione generazionale. 
---
= Generazioni di design
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La soluzione BeeGFS su NetApp si trova attualmente nella sua seconda progettazione generazionale.

Sia la prima che la seconda generazione includono un'architettura di base che incorpora un file system BeeGFS e un sistema storage NVMe EF600. Tuttavia, la seconda generazione si basa sulla prima per includere questi benefici aggiuntivi:

* Raddoppiare le prestazioni e la capacità aggiungendo solo 2U di spazio rack
* Alta disponibilità (ha) basata su un design hardware a due livelli e a disco condiviso
* Architettura progettata per i sistemi NVIDIA DGX SuperPOD A100, H100, H200 e B200, precedentemente validata in un cluster di accettazione dedicato di NVIDIA. Ulteriori informazioni su NVIDIA DGX SuperPOD with NetApp nel link:https://docs.netapp.com/us-en/netapp-solutions/ai/ai-dgx-superpod.html["guida alla progettazione"].




== Secondo design generazionale

La seconda generazione di BeeGFS su NetApp è ottimizzata per soddisfare i requisiti di performance dei carichi di lavoro esigenti, tra cui high-performance computing (HPC), machine learning (ML), deep learning (DL) e altre tecniche di intelligenza artificiale (ai). Grazie all'integrazione di un'architettura ha (High Availability, alta disponibilità) a disco condiviso, questo design garantisce la durata e la disponibilità dei dati, rendendoli ideali per le aziende e altre organizzazioni che non possono permettersi downtime o perdite di dati. Il design di seconda generazione include componenti quali i server PCIe Gen5 e il supporto per gli switch NVIDIA® Quantum™ InfiniBand da QM9700 400GB GB/s. Questa soluzione non solo è stata verificata da NetApp, ma ha anche superato la qualifica esterna come opzione di storage per NVIDIA DGX™ A100 SuperPOD, con certificazione estesa per i sistemi DGX SuperPOD H100, H200 e B200.



== Primo design generazionale

La prima generazione di BeeGFS su NetApp è stata progettata per i workload di machine learning (ML) e intelligenza artificiale (ai) utilizzando i sistemi di storage NVMe NetApp EF600, il file system parallelo BeeGFS, i sistemi NVIDIA DGX™ A100 e gli switch IB NVIDIA® Mellanox® Quantum™ QM8700 200GB/s. Questo design include anche InfiniBand (IB) a 200GB GB/s per il fabric di interconnessione del cluster di storage e calcolo, per offrire un'architettura completamente basata su IB per workload a performance elevate.

Per ulteriori informazioni sulla prima generazione, vedere link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["NetApp EF-Series ai con sistemi NVIDIA DGX A100 e BeeGFS"^].
