---
sidebar: sidebar 
permalink: beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Per impostare un nodo di controllo Ansible, identificare una macchina virtuale o fisica con accesso di rete alle porte di gestione di tutti i nodi di file e blocchi che possono essere utilizzati per configurare la soluzione. 
---
= Impostare un nodo di controllo Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per impostare un nodo di controllo Ansible, è necessario identificare una macchina virtuale o fisica con accesso di rete alle porte di gestione di tutti i nodi di file e blocchi che possono essere utilizzati per configurare la soluzione.

I seguenti passaggi sono stati testati su Ubuntu 22,04. Per i passaggi specifici della distribuzione Linux preferita, vedere https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Documentazione Ansible"^].

. Installare Python 3,10 e assicurarsi che sia installata la versione corretta di `pip` .
+
....
sudo apt install python3.10 -y
sudo apt install python3-pip
sudo apt install sshpass
....
. Creare collegamenti simbolici, assicurandosi che il binario Python 3,10 venga utilizzato ogni volta che `python3` viene chiamato o `python` .
+
....
sudo ln -sf /usr/bin/python3.10 /usr/bin/python3
sudo ln -sf /usr/bin/python3 /usr/bin/python
....
. Installare i pacchetti Python richiesti dalle raccolte NetApp BeeGFS.
+
....
python3 -m pip install ansible cryptography netaddr
....
+

NOTE: Per assicurarsi di installare una versione supportata di Ansible e tutti i pacchetti Python richiesti, fare riferimento al file Readme della raccolta BeeGFS. Le versioni supportate sono indicate anche nella link:beegfs-technology-requirements.html["Requisiti tecnici"].

. Verificare che siano installate le versioni corrette di Ansible e Python.
+
....
ansible --version
ansible [core 2.17.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
....
. Memorizzare gli inventari Ansible utilizzati per descrivere l'implementazione di BeeGFS nei sistemi di controllo del codice sorgente come Git o BitBucket, quindi installare Git per interagire con tali sistemi.
+
....
sudo apt install git -y
....
. Impostare SSH senza password. Questo è il modo più semplice per consentire ad Ansible di accedere ai nodi di file BeeGFS remoti dal nodo di controllo Ansible.
+
.. Nel nodo di controllo Ansible, se necessario, generare una coppia di chiavi pubbliche utilizzando `ssh-keygen`
.. Impostare SSH senza password su ciascuno dei nodi di file utilizzando `ssh-copy-id <ip_or_hostname>`
+
Non impostare * SSH senza password sui nodi di blocco. Questo non è supportato né richiesto.



. Utilizzare Ansible Galaxy per installare la versione della raccolta BeeGFS elencata nella link:beegfs-technology-requirements.html["Requisiti tecnici"].
+
Questa installazione include dipendenze Ansible aggiuntive, come il software NetApp SANtricity e le raccolte host.

+
....
ansible-galaxy collection install netapp_eseries.beegfs:==3.2.0
....

