---
sidebar: sidebar 
permalink: second-gen/beegfs-technology-requirements.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Per implementare la soluzione BeeGFS su NetApp, assicurati che il tuo ambiente soddisfi i requisiti tecnologici. 
---
= Requisiti tecnici
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per implementare la soluzione BeeGFS su NetApp, accertatevi che l'ambiente soddisfi i requisiti tecnologici descritti nel presente documento.



== Panoramica dei requisiti

Questa pagina descrive in dettaglio i requisiti hardware, software e firmware per l'implementazione di BeeGFS sui NetApp building block. I requisiti sono organizzati nelle seguenti sezioni:

* <<Requisiti hardware>> - Nodi file (hardware/software/firmware), nodi a blocchi (hardware/firmware), networking e cablaggio
* <<Requisiti di implementazione del software>> - Componenti distribuiti tramite Ansible
* <<Requisiti dei nodi di controllo Ansible>> - Versioni del software del nodo di controllo




== Requisiti hardware

Prima di iniziare, assicurati che l'hardware soddisfi le seguenti specifiche per una progettazione di building block singolo della soluzione BeeGFS su NetApp. I componenti esatti per una particolare implementazione possono variare in base ai requisiti del cliente. Ogni nodo file deve soddisfare o superare queste specifiche per ottenere le prestazioni previste.



=== Requisiti del nodo del file

[cols="10%,90%"]
|===
| Quantità | Specifiche 


| 2  a| 
*Lenovo ThinkSystem SR665 V3*

*Hardware:*

* *Processori:* 2x AMD EPYC 9124 16C 3.0 GHz (configurati come due NUMA zone)
* *Memoria:* 256GB GB (16x 16GB TruDDR5 4800MHz RDIMM-A)
* *Espansione PCIe:* quattro slot PCIe Gen5 x16 (due per zona NUMA)
* *Schede HCA:* 4x MCX755106AS-HEAT ConnectX-7, NDR200, QSFP112, 2-port, PCIe Gen5 x16, InfiniBand Adapter
* *Archiviazione:* Due unità in RAID 1 per OS (1TB 7.2K SATA o superiore)
* *Gestione:* Porta 1GbE per la gestione in banda del sistema operativo
* *BMC:* 1GbE BMC con API Redfish per la gestione del server fuori banda
* *Alimentazione:* Doppi alimentatori swap a caldo e ventole ad alte prestazioni


*Software e Firmware:*

* *Sistema operativo:* Red Hat 9.4 Server fisico con High Availability (2 socket)
* *Kernel Linux:* 5.14.0-427.42.1.el9_4.x86_64
* *Firmware HCA:* FW: 28.46.1006, PXE: 3.8.0100, UEFI: 14.39.0013


|===

IMPORTANT: I nodi file richiedono un abbonamento valido a Red Hat Enterprise Linux Server e il Red Hat Enterprise Linux High Availability Add-On.



=== Requisiti del nodo block

Ogni building block richiede due array E-Series dello stesso modello. Non mescolare modelli di array all'interno dello stesso building block.

[cols="10%,20%,70%"]
|===
| Quantità | Modello | Specifiche 


| 2 | EF80  a| 
*Hardware:*

* *Memoria:* 128GB (64GB per controller)
* *Adattatore:* 2x 2-port 200Gb/NDR (NVMe/IB)
* *Unità:* Configurate per corrispondere ai metadati e alla capacità di archiviazione desiderata


*Firmware:*

* *SANtricity OS:* 12.00
* *NVSRAM:* NEF80-200834-D00
* *Firmware dell'unità:* Ultima disponibile per i tuoi modelli di unità (vedi link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["Sito del firmware del disco E-Series"^])




| 2 | EF600  a| 
*Hardware:*

* *Memoria:* 256GB (128GB per controller)
* *Adattatore:* 2-port 200Gb/HDR (NVMe/IB)
* *Unità:* Configurate per corrispondere ai metadati e alla capacità di archiviazione desiderata


*Firmware:*

* *SANtricity OS:* 11.90R5
* *NVSRAM:* N6000-890834-D02
* *Firmware dell'unità:* Ultima disponibile per i tuoi modelli di unità (vedi link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["Sito del firmware del disco E-Series"^])


|===


=== Requisiti degli switch di rete di archiviazione

[cols="10%,90%"]
|===
| Quantità | Specifiche 


| 1  a| 
*Switch NVIDIA QM9700 Quantum 2 NDR InfiniBand*

Lo switch di rete deve essere in grado di raggiungere velocità InfiniBand di 200Gb/s. Il NVIDIA QM9700 è lo switch consigliato per il cluster.

|===

NOTE: Switch alternativi come l'NVIDIA MQM8700 Quantum possono essere utilizzati, ma richiedono un cablaggio diverso.



=== Requisiti di cablaggio



==== Cavi da nodo di blocco a nodo file

Le connessioni dirette dai nodi a blocchi ai nodi file richiedono i seguenti cavi:

[cols="15%,60%,25%"]
|===
| Quantità | Specifiche del cavo | Lunghezza 


| 8 | MCP1650-H001E30 - Cavo in rame passivo NVIDIA, QSFP56, 200Gb/s | 1 m 
|===


==== Cavi da nodo file a switch di storage

Per lo switch NVIDIA QM9700 Quantum 2 si consigliano i seguenti tipi di cavo. Scegliere tra fibra attiva o rame passivo in base alle proprie esigenze. Le quantità si riferiscono a ciascun building block.

[cols="20%,15%,10%,55%"]
|===
| Modello di switch | Tipo di cavo | Quantità | Codice ricambio 


.4+| NVIDIA QM9700 .3+| Fibra attiva (inclusi i ricetrasmettitori) | 2 | MMA4Z00-NS (multimodale, IB/ETH, 800GB GB/s 2x400 GB/s a due porte OSFP) 


| 4 | MFP7E20-Nxxx (cavo in fibra splitter multimodale da 4 canali a due a 2 canali) 


| 8 | MMA1Z00-NS400 (multimodale, IB/ETH, QSFP-112 a una porta da 400GB GB/s) 


| Rame passivo | 2 | MCP7Y40-N002 (cavo splitter in rame passivo NVIDIA, da InfiniBand 800GB GB/s a 4x 200GB GB/s, da OSFP a 4x QSFP112) 
|===


=== Requisiti di implementazione del software

La seguente tabella elenca i requisiti software implementati automaticamente nell'ambito dell'implementazione di Ansible-Based BeeGFS.

[cols="20%,80%"]
|===
| Software | Versione 


| BeeGFS | 8.2.2 


| Corosync | 3.1.8-1 


| Pacemaker | 2.1.7-5,2 


| Agenti di recinzione (scorfano rosso/apc) | 4.10.0-62 


| Driver InfiniBand/RDMA | DOCA-OFED-25.04-0.6.1 
|===


=== Requisiti dei nodi di controllo Ansible

La soluzione BeeGFS su NetApp viene implementata e gestita da un nodo di controllo Ansible. Per ulteriori informazioni, consultare https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html["Documentazione Ansible"^].

I requisiti software elencati nelle tabelle seguenti sono specifici della versione della raccolta NetApp BeeGFS Ansible elencata di seguito.

[cols="30%,70%"]
|===
| Software | Versione 


| Ansible-core | >= 2.19.0 


| Python | 3,12 


| Pacchetti Python aggiuntivi | Cryptography-46.0.3, netaddr-1.3.0, ipaddr-2.2.0 


| Raccolta Ansible BeeGFS NetApp E-Series | 4.0.0 
|===