---
sidebar: sidebar 
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-prereqs.html 
keywords: BeeGFS Features, CSI, Driver 
summary: Prerequisiti per distribuire il driver CSI BeeGFS 
---
= Prerequisiti per distribuire il driver CSI BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Prima di distribuire e configurare il driver CSI BeeGFS, assicurati di avere un cluster Kubernetes in esecuzione, di avere accesso al cluster BeeGFS e di disporre delle autorizzazioni appropriate per installare le risorse a livello di cluster.



== Verifica la configurazione di Kubernetes

Esegui il seguente comando per verificare lo stato dei pod nel tuo cluster Kubernetes:

[source, console]
----
kubectl get pods
----
**Risultato previsto:**

[listing]
----
root@node01:/etc/cni/net.d# kubectl get pods
No resources found in default namespace.
----
Se non ci sono pod in esecuzione, l'elenco sarà vuoto.  In caso contrario, i pod dovrebbero essere elencati senza errori.



== Convalida del client e dei servizi BeeGFS

Verificare che il cluster BeeGFS sia integro e che tutti i servizi siano raggiungibili eseguendo il seguente comando:

**BeeGFS 7.4**

[source, console]
----
beegfs-check-servers
----
**BeeGFS 8**

[source, console]
----
beegfs health check
----

NOTE: Il driver CSI funziona con entrambi `beegfs-dkms-client` E `beegfs-client` , che deve essere installato su ogni nodo Kubernetes.  Per la procedura di installazione, consultare la documentazione DKMS del client BeeGFS: https://doc.beegfs.io/latest/advanced_topics/client_dkms.html[]

**Output previsto per BeeGFS 7.4:**

[listing]
----
root@node01:/home/user_id/beegfs-csi-driver# beegfs-check-servers
Management
==========
mgmt [ID: 1]: reachable at XXX.X.AB.1:8008 (protocol: TCP)

Metadata
==========
meta_25_tgt_2501 [ID: 2501]: reachable at XXX.X.AA.MN:8255 (protocol: RDMA)
meta_26_tgt_2601 [ID: 2601]: reachable at XXX.X.BB.NO:8265 (protocol: RDMA)
meta_27_tgt_2701 [ID: 2701]: reachable at XXX.X.AA.OP:8275 (protocol: RDMA)
meta_28_tgt_2801 [ID: 2801]: reachable at XXX.X.BB.PQ:8285 (protocol: RDMA)
meta_29_tgt_2901 [ID: 2901]: reachable at XXX.X.AA.QR:8295 (protocol: RDMA)
meta_30_tgt_3001 [ID: 3001]: reachable at XXX.X.BB.RS:8305 (protocol: RDMA)
meta_31_tgt_3101 [ID: 3101]: reachable at XXX.X.AA.ST:8315 (protocol: RDMA)
meta_32_tgt_3201 [ID: 3201]: reachable at XXX.X.BB.TU:8325 (protocol: RDMA)

Storage
==========
stor_25_tgt_2501 [ID: 2501]: reachable at XXX.X.CC.MN:8253 (protocol: RDMA)
stor_26_tgt_2601 [ID: 2601]: reachable at XXX.X.DD.NO:8263 (protocol: RDMA)
stor_27_tgt_2701 [ID: 2701]: reachable at XXX.X.CC.OP:8273 (protocol: RDMA)
stor_28_tgt_2801 [ID: 2801]: reachable at XXX.X.DD.PQ:8283 (protocol: RDMA)
stor_29_tgt_2901 [ID: 2901]: reachable at XXX.X.CC.QR:8293 (protocol: RDMA)
stor_30_tgt_3001 [ID: 3001]: reachable at XXX.X.DD.RS:8303 (protocol: RDMA)
stor_31_tgt_3101 [ID: 3101]: reachable at XXX.X.CC.ST:8313 (protocol: RDMA)
stor_32_tgt_3201 [ID: 3201]: reachable at XXX.X.DD.32:8323 (protocol: RDMA)
----
Se uno qualsiasi dei servizi non è raggiungibile, assicurarsi che il client BeeGFS sia configurato correttamente e che la connettività di rete ai server BeeGFS sia funzionante.
