---
sidebar: sidebar 
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-verify.html 
keywords: BeeGFS Features, CSI, Driver 
summary: Verifica della distribuzione del driver CSI BeeGFS. 
---
= Verifica della distribuzione del driver CSI BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per verificare che il driver CSI BeeGFS sia stato distribuito correttamente, controllare lo stato dei pod del driver CSI e confermare che funzionino come previsto.

Per controllare lo stato di tutte le risorse nello spazio dei nomi BeeGFS-CSI, eseguire:

[source, console]
----
kubectl get all -n beegfs-csi
----
**Risultato previsto:**

[listing]
----
NAME                          READY    STATUS      RESTARTS    AGE
pod/csi-beegfs-controller-0   3/3      Running     0           5d11h
pod/csi-beegfs-node-8f917     3/3      Running     0           5d11h
----


== Ispezionare il Controller Pod

Per diagnosticare problemi o raccogliere maggiori dettagli sul pod BeeGFS CSI Controller, utilizzare il seguente comando per descrivere il pod e rivedere i suoi eventi, lo stato e l'attività recente:

[source, console]
----
kubectl describe pod csi-beegfs-controller-0 -n beegfs-csi
----
**Risultato previsto:**

[listing]
----
Events:

  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  117s                 default-scheduler  Successfully assigned beegfs-csi/csi-beegfs-controller-0 to node01
  Normal   Pulled     117s                 kubelet            Container image "registry.k8s.io/sig-storage/csi-provisioner:v3.5.0" already present on machine
  Normal   Created    117s                 kubelet            Created container: csi-provisioner
  Normal   Started    117s                 kubelet            Started container csi-provisioner
  Normal   Started    101s (x3 over 117s)  kubelet            Started container beegfs
  Normal   Pulled     86s (x2 over 117s)   kubelet            Container image "registry.k8s.io/sig-storage/csi-resizer:v1.11.1" already present on machine
  Normal   Created    86s (x2 over 117s)   kubelet            Created container: csi-resizer
  Normal   Started    86s (x2 over 117s)   kubelet            Started container csi-resizer
  Warning  BackOff    85s (x5 over 115s)   kubelet            Back-off restarting failed container beegfs in pod csi-beegfs-controller-0_beegfs-csi(47016fd3-3a2a-41ed-bc4c-5a716c377b1e)
  Normal   Pulled     73s (x4 over 117s)   kubelet            Container image "ghcr.io/thinkparq/beegfs-csi-driver:v1.7.0" already present on machine
  Normal   Created    73s (x4 over 117s)   kubelet            Created container: beegfs
----


== Verifica StorageClass

. Convalida che StorageClass sia stato creato correttamente:
+
[source, console]
----
kubectl get sc
----
+
**Risultato previsto:**

+
[listing]
----
root@node01:/home/user_id/beegfs-csi-driver# kubectl get sc
NAME                PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-beegfs-dyn-sc   beegfs.csi.org.com   Delete          Immediate           true                   17s
----
. Verificare che il volume BeeGFS sia montato come previsto.
+
Verificare la directory specificata come `volDirBasePath` In `examples/k8s/dyn/dyn-sc.yaml` appare sotto `/mnt/beegfs` .

+
Ad esempio, se `volDirBasePath` è impostato su `user_id_k8s` , dovresti vedere elencata questa directory:

+
[source, console]
----
root@node01:/# ls -ltr /mnt/beegfs/
total 1
drwxrwxrwx 4 root root 2 Oct 15 10:16 user_id_k8s
----

