---
sidebar: sidebar 
permalink: administer/clusters-ansible-pcs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, pcs, Ansible 
summary: Quando si deve utilizzare Ansible rispetto allo strumento della riga di comando di PC per gestire il cluster ha? 
---
= Quando utilizzare Ansible rispetto allo strumento PC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Quando si deve utilizzare Ansible rispetto allo strumento della riga di comando di PC per gestire il cluster ha?

Tutte le attività di implementazione e riconfigurazione del cluster devono essere completate utilizzando Ansible da un nodo di controllo Ansible esterno. Le modifiche temporanee nello stato del cluster (ad esempio, l'inserimento e l'uscita dei nodi in standby) vengono eseguite in genere accedendo a un nodo del cluster (preferibilmente uno che non è degradato o che sta per essere sottoposto a manutenzione) e utilizzando la riga di comando di PC.

La modifica di qualsiasi configurazione del cluster, incluse risorse, vincoli, proprietà e i servizi BeeGFS stessi, deve essere eseguita sempre utilizzando Ansible. La manutenzione di una copia aggiornata dell'inventario e del playbook Ansible (idealmente nel controllo del codice sorgente per tenere traccia delle modifiche) fa parte della manutenzione del cluster. Quando è necessario apportare modifiche alla configurazione, aggiornare l'inventario ed eseguire nuovamente il playbook Ansible che importa il ruolo BeeGFS ha.

Il ruolo ha gestirà il posizionamento del cluster in modalità di manutenzione e l'esecuzione delle modifiche necessarie prima di riavviare BeeGFS o i servizi cluster per applicare la nuova configurazione. Poiché i riavvii completi dei nodi non sono generalmente necessari al di fuori dell'implementazione iniziale, il rerunning di Ansible è generalmente considerato una procedura "sicura", ma è sempre consigliato durante le finestre di manutenzione o fuori orario nel caso in cui sia necessario riavviare qualsiasi servizio BeeGFS. In genere, questi riavvii non dovrebbero causare errori nelle applicazioni, ma potrebbero compromettere le prestazioni (che alcune applicazioni potrebbero gestire meglio di altre).

Il rerunning di Ansible è anche un'opzione quando si desidera riportare l'intero cluster a uno stato completamente ottimale e in alcuni casi potrebbe essere in grado di ripristinare lo stato del cluster più facilmente rispetto all'utilizzo di PC. Soprattutto in caso di emergenza in cui il cluster non è attivo per qualche motivo, una volta eseguito il backup di tutti i nodi, Ansible può ripristinare il cluster in modo più rapido e affidabile rispetto al tentativo di utilizzare i PC.
