---
sidebar: sidebar 
permalink: administer/clusters-update-beegfs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade 
summary: Utilizzare Ansible per aggiornare BeeGFS e il cluster ha. 
---
= Aggiornare la versione BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Segui questi passaggi per aggiornare la versione BeeGFS del cluster ha utilizzando Ansible.



== Panoramica

BeeGFS segue uno `major.minor.patch` schema di versioning. I ruoli Ansible ha BeeGFS sono forniti per ogni `major.minor` versione supportata (ad esempio, `beegfs_ha_7_2` e `beegfs_ha_7_3`). Ogni ruolo ha è associato all'ultima versione della patch BeeGFS disponibile al momento della release della raccolta Ansible.

Ansible deve essere utilizzato per tutti gli aggiornamenti di BeeGFS, incluso il passaggio tra le versioni principali, minori e patch di BeeGFS. Per aggiornare BeeGFS, è necessario innanzitutto aggiornare la raccolta BeeGFS Ansible, che include anche le correzioni e i miglioramenti più recenti all'automazione della distribuzione/gestione e al cluster ha sottostante. Anche dopo l'aggiornamento alla versione più recente della raccolta, BeeGFS non verrà aggiornato fino a. `ansible-playbook` viene eseguito con `-e "beegfs_ha_force_upgrade=true"` impostare.


NOTE: Per ulteriori informazioni sulle versioni di BeeGFS, vedere link:https://doc.beegfs.io/latest/advanced_topics/upgrade.html["Documentazione sull'aggiornamento di BeeGFS"^].



== Percorsi di aggiornamento testati

Ogni versione dell'insieme BeeGFS viene testata con versioni specifiche di BeeGFS per garantire l'interoperabilità tra tutti i componenti. Viene inoltre eseguito un test per garantire che gli aggiornamenti possano essere eseguiti dalle versioni di BeeGFS supportate dall'ultima versione della raccolta a quelle supportate nell'ultima release.

[cols="1,1,1,5"]
|===
| Versione originale | Versione dell'aggiornamento | Multirrail | Dettagli 


| 7.2.6 | 7.3.2 | Sì | Aggiornamento della raccolta beegfs da v3.0.1 a v3.1.0, aggiunta di multi-rail 


| 7.2.6 | 7.2.8 | No | Aggiornamento della raccolta beegfs da v3.0.1 a v3.1.0 


| 7.2.8 | 7.3.1 | Sì | Aggiornamento con la raccolta beegfs v3.1.0, aggiunta di multi-rail 


| 7.3.1 | 7.3.2 | Sì | Eseguire l'aggiornamento utilizzando la raccolta beegfs v3.1.0 


| 7.3.2 | 7.4.1 | Sì | Eseguire l'aggiornamento utilizzando la raccolta beegfs v3.2.0 


| 7.4.1 | 7.4.2 | Sì | Eseguire l'aggiornamento utilizzando la raccolta beegfs v3.2.0 
|===


== Fasi di aggiornamento di BeeGFS

Nelle sezioni seguenti sono riportati i passaggi per aggiornare la raccolta BeeGFS Ansible e BeeGFS stessa. Prestare particolare attenzione a eventuali passaggi aggiuntivi per l'aggiornamento delle versioni principali o secondarie di BeeGFS.



=== Passaggio 1: Aggiornamento della raccolta BeeGFS

Per gli aggiornamenti del ritiro con accesso a. link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible Galaxy"^], eseguire il seguente comando:

[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs --upgrade
----
Per gli aggiornamenti offline della raccolta, scarica la raccolta da link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible Galaxy"^] facendo clic sul pulsante desiderato `Install Version`` e poi `Download tarball`. Trasferire il tarball al nodo di controllo Ansible ed eseguire il seguente comando.

[source, console]
----
ansible-galaxy collection install netapp_eseries-beegfs-<VERSION>.tar.gz --upgrade
----
Vedere link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html["Installazione delle raccolte"^] per ulteriori informazioni.



=== Fase 2: Aggiornare l'inventario Ansible

Eseguire gli aggiornamenti necessari o desiderati ai file di inventario Ansible del cluster. Per link:clusters-update-beegfs.html#version-upgrade-notes["Note sull'aggiornamento della versione"]ulteriori informazioni sui requisiti specifici per l'aggiornamento, vedere la sezione seguente. Vedere la link:../custom/architectures-inventory-overview.html["Panoramica di Ansible Inventory"^] sezione per informazioni generali sulla configurazione dell'inventario BeeGFS ha.



=== Fase 3: Aggiornamento del playbook Ansible (solo per l'aggiornamento delle versioni principali o secondarie)

Se si passa da una versione principale a una versione secondaria, nel `playbook.yml` file utilizzato per distribuire e gestire il cluster, aggiornare il nome del `beegfs_ha_<VERSION>` ruolo in modo che rifletta la versione desiderata. Ad esempio, se si desidera distribuire BeeGFS 7,4 questo sarà `beegfs_ha_7_4`:

[source, yaml]
----
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.beegfs
  tasks:
    - name: Ensure BeeGFS HA cluster is setup.
      ansible.builtin.import_role:  # import_role is required for tag availability.
        name: beegfs_ha_7_4
----
Per ulteriori dettagli sul contenuto del file del presente manuale, consulta link:../custom/architectures-deploy-ha-cluster.html["Implementare il cluster BeeGFS ha"^]la sezione.



=== Passaggio 4: Eseguire l'aggiornamento BeeGFS

Per applicare l'aggiornamento BeeGFS:

[source, console]
----
ansible-playbook -i inventory.yml beegfs_ha_playbook.yml -e "beegfs_ha_force_upgrade=true" --tags beegfs_ha
----
Dietro le quinte, il ruolo di BeeGFS ha gestirà:

* Assicurarsi che il cluster si trovi in uno stato ottimale con ciascun servizio BeeGFS situato sul nodo preferito.
* Impostare il cluster in modalità di manutenzione.
* Aggiornare i componenti del cluster ha (se necessario).
* Aggiornare ciascun nodo di file uno alla volta come segue:
+
** Metterlo in standby e eseguire il failover dei servizi sul nodo secondario.
** Aggiornare i pacchetti BeeGFS.
** Servizi di fallback.


* Spostare il cluster fuori dalla modalità di manutenzione.




== Note sull'aggiornamento della versione



=== Aggiornamento da BeeGFS versione 7.2.6 o 7.3.0



==== Modifiche all'autenticazione basata su connessione

Le versioni di BeeGFS rilasciate dopo la 7.3.1 non consentono più l'avvio dei servizi senza specificare un `connAuthFile` o impostazione `connDisableAuthentication=true` nel file di configurazione del servizio. Si consiglia vivamente di attivare la protezione dell'autenticazione basata sulla connessione. Vedere link:https://doc.beegfs.io/7.3.2/advanced_topics/authentication.html#connectionbasedauth["Autenticazione basata su connessione BeeGFS"^] per ulteriori informazioni.

Per impostazione predefinita, il `beegfs_ha*` I ruoli genereranno e distribuiranno questo file, aggiungendolo anche al nodo di controllo Ansible all'indirizzo `<playbook_directory>/files/beegfs/<beegfs_mgmt_ip_address>_connAuthFile`. Il `beegfs_client` role verificherà anche la presenza di questo file e lo fornirà ai client, se disponibili.


WARNING: Se il `beegfs_client` il ruolo non è stato utilizzato per configurare i client; questo file deve essere distribuito manualmente a ciascun client e a. `connAuthFile` configurazione in `beegfs-client.conf` file impostato per utilizzarlo. Quando si esegue l'aggiornamento da una versione precedente di BeeGFS in cui l'autenticazione basata sulla connessione non era abilitata, i client perderanno l'accesso a meno che l'autenticazione basata sulla connessione non sia disattivata come parte dell'aggiornamento mediante l'impostazione `beegfs_ha_conn_auth_enabled: false` poll `group_vars/ha_cluster.yml` (sconsigliato).

Per ulteriori dettagli e opzioni di configurazione alternative, vedere la procedura per configurare l'autenticazione della connessione nella link:../custom/architectures-inventory-common-file-node-configuration.html["Specificare la configurazione del nodo file comune"^]sezione .
