---
sidebar: sidebar 
permalink: administer/clusters-maintenance-mode.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, maintenance 
summary: 'Evitare che il cluster ha reagisca accidentalmente alle modifiche previste nell"ambiente.' 
---
= Impostare il cluster in modalità di manutenzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Evitare che il cluster ha reagisca accidentalmente alle modifiche previste nell'ambiente.



== Panoramica

Impostando il cluster in modalità di manutenzione si disattiva il monitoraggio di tutte le risorse e si impedisce a Pacemaker di spostare o gestire in altro modo le risorse nel cluster. Tutte le risorse rimarranno in esecuzione sui nodi originali, indipendentemente dalla presenza di una condizione di guasto temporanea che ne impedirebbe l'accesso. Gli scenari in cui questo è consigliato/utile includono:

* Manutenzione della rete che potrebbe interrompere temporaneamente le connessioni tra i nodi di file e i servizi BeeGFS.
* Aggiornamenti del nodo a blocchi.
* File Node per aggiornamenti di sistemi operativi, kernel o altri pacchetti.


In genere, l'unico motivo per attivare manualmente la modalità di manutenzione è impedire che il cluster reagisca alle modifiche esterne dell'ambiente. Se un singolo nodo del cluster richiede una riparazione fisica, non utilizzare la modalità di manutenzione e posizionare semplicemente tale nodo in standby seguendo la procedura descritta in precedenza. Si noti che la riesecuzione di Ansible attiva automaticamente la modalità di manutenzione del cluster, facilitando la maggior parte della manutenzione del software, inclusi aggiornamenti e modifiche alla configurazione.



== Fasi

Per verificare se il cluster è in modalità di manutenzione, eseguire:

[source, console]
----
pcs property config
----
La `maintenance-mode` proprietà non viene visualizzata se il cluster funziona normalmente. Se il cluster è attualmente in modalità di manutenzione, la proprietà visualizzerà come `true`. Per attivare la modalità di manutenzione, eseguire:

[source, console]
----
pcs property set maintenance-mode=true
----
Puoi verificare eseguendo lo stato dei PC e assicurandoti che tutte le risorse mostrino "(unmanaged)". Per uscire dalla modalità di manutenzione del cluster, eseguire:

[source, console]
----
pcs property set maintenance-mode=false
----