---
sidebar: sidebar 
permalink: administer/clusters-reconfigure.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, Ansible, pcs 
summary: Utilizzare Ansible per riconfigurare il cluster. 
---
= Riconfigurare il cluster ha e BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilizzare Ansible per riconfigurare il cluster.



== Panoramica

In genere, la riconfigurazione di qualsiasi aspetto del cluster ha BeeGFS deve essere eseguita aggiornando l'inventario Ansible ed eseguendo nuovamente il `ansible-playbook` comando. Ciò include l'aggiornamento degli avvisi, la modifica della configurazione di scherma permanente o la regolazione della configurazione del servizio BeeGFS. Questi vengono regolati utilizzando il `group_vars/ha_cluster.yml` file e un elenco completo delle opzioni è disponibile nella link:../custom/architectures-inventory-common-file-node-configuration.html["Specificare la configurazione del nodo file comune"^]sezione .

Per ulteriori informazioni sulle opzioni di configurazione selezionate di cui gli amministratori devono essere a conoscenza durante la manutenzione o la manutenzione del cluster, vedere di seguito.



== Come disattivare e attivare la funzione di scherma

Per impostazione predefinita, la funzione di scherma viene attivata/richiesta durante la configurazione del cluster. In alcuni casi, potrebbe essere consigliabile disattivare temporaneamente la scherma per garantire che i nodi non vengano accidentalmente arrestati durante determinate operazioni di manutenzione (ad esempio l'aggiornamento del sistema operativo). Anche se questa funzione può essere disattivata manualmente, gli amministratori devono tenere presente che esistono compromessi.



=== OPZIONE 1: Disattiva scherma utilizzando Ansible (consigliato).

Quando la funzione di scherma viene disattivata utilizzando Ansible, l'azione on-fail del monitor BeeGFS passa da "fence" a "standby". Ciò significa che se il monitor BeeGFS rileva un errore, tenterà di mettere il nodo in standby e di eseguire il failover di tutti i servizi BeeGFS. Al di fuori del troubleshooting/test attivo, questo è in genere più desiderabile dell'opzione 2. Lo svantaggio è che se una risorsa non si ferma sul nodo originale, viene impedita l'avvio da un'altra parte (motivo per cui la scherma è generalmente richiesta per i cluster di produzione).

. Nel tuo inventario Ansible all'indirizzo `groups_vars/ha_cluster.yml` aggiungere la seguente configurazione:
+
[source, console]
----
beegfs_ha_cluster_crm_config_options:
    stonith-enabled: False
----
. Rieseguire il manuale Ansible per applicare le modifiche al cluster.




=== OPZIONE 2: Disattiva manualmente la funzione di scherma.

In alcuni casi, potrebbe essere necessario disattivare temporaneamente la scherma senza eseguire nuovamente Ansible, ad esempio per facilitare la risoluzione dei problemi o il test del cluster.


WARNING: In questa configurazione, se il monitor BeeGFS rileva un errore, il cluster tenta di arrestare il gruppo di risorse corrispondente. Non attiverà un failover completo né tenterà di riavviare o spostare il gruppo di risorse interessato in un altro host. Per risolvere il problema, risolvere i problemi che si verificano in seguito `pcs resource cleanup` oppure mettere manualmente il nodo in standby.

Fasi:

. Per determinare se la scherma (stonith) è attivata o disattivata globalmente, eseguire: `pcs property show stonith-enabled`
. Per disattivare la funzione di scherma: `pcs property set stonith-enabled=false`
. Per attivare la funzione di scherma: `pcs property set stonith-enabled=true`


Nota: Questa impostazione verrà ignorata alla prossima esecuzione del playbook Ansible.
