---
sidebar: sidebar 
permalink: administer/clusters-upgrade-beegfs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade 
summary: Utilizzare Ansible per aggiornare BeeGFS e il cluster ha. 
---
= Aggiorna i servizi BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilizzare Ansible per aggiornare la versione di BeeGFS in esecuzione sul cluster HA.



== Panoramica

BeeGFS segue uno `major.minor.patch` schema di versioning. I ruoli Ansible ha BeeGFS sono forniti per ogni `major.minor` versione supportata (ad esempio, `beegfs_ha_7_2` e `beegfs_ha_7_3`). Ogni ruolo ha è associato all'ultima versione della patch BeeGFS disponibile al momento della release della raccolta Ansible.

Ansible deve essere utilizzato per tutti gli aggiornamenti di BeeGFS, incluso il passaggio tra versioni principali, secondarie e patch di BeeGFS. Per aggiornare BeeGFS, è necessario innanzitutto aggiornare la raccolta Ansible di BeeGFS, che includerà anche le ultime correzioni e miglioramenti all'automazione di distribuzione/gestione e al cluster HA sottostante. Anche dopo l'aggiornamento all'ultima versione della raccolta, BeeGFS non verrà aggiornato finché  `ansible-playbook` non verrà eseguito con il  `-e "beegfs_ha_force_upgrade=true"` set. Per ulteriori dettagli su ciascun aggiornamento, fare riferimento alla link:https://doc.beegfs.io/latest/advanced_topics/upgrade.html["Documentazione sull'aggiornamento di BeeGFS"^] per la versione corrente.


NOTE: Se si sta eseguendo l'aggiornamento a BeeGFS v8, consultare la link:clusters-upgrade-beegfs-v8.html["Aggiorna a BeeGFS v8"] procedura invece.



== Percorsi di aggiornamento testati

Sono stati testati e verificati i seguenti percorsi di aggiornamento:

[cols="1,1,1,5"]
|===
| Versione originale | Versione dell'aggiornamento | Multirrail | Dettagli 


| 7.2.6 | 7.3.2 | Sì | Aggiornamento della raccolta beegfs da v3.0.1 a v3.1.0, aggiunta di multi-rail 


| 7.2.6 | 7.2.8 | No | Aggiornamento della raccolta beegfs da v3.0.1 a v3.1.0 


| 7.2.8 | 7.3.1 | Sì | Aggiornamento con la raccolta beegfs v3.1.0, aggiunta di multi-rail 


| 7.3.1 | 7.3.2 | Sì | Eseguire l'aggiornamento utilizzando la raccolta beegfs v3.1.0 


| 7.3.2 | 7.4.1 | Sì | Eseguire l'aggiornamento utilizzando la raccolta beegfs v3.2.0 


| 7.4.1 | 7.4.2 | Sì | Eseguire l'aggiornamento utilizzando la raccolta beegfs v3.2.0 


| 7.4.2 | 7.4.6 | Sì | Eseguire l'aggiornamento utilizzando la raccolta beegfs v3.2.0 


| 7.4.6 | 8,0 | Sì | Eseguire l'aggiornamento utilizzando le istruzioni nella link:clusters-upgrade-beegfs-v8.html["Aggiorna a BeeGFS v8"] procedura. 


| 7.4.6 | 8,1 | Sì | Eseguire l'aggiornamento utilizzando le istruzioni nella link:clusters-upgrade-beegfs-v8.html["Aggiorna a BeeGFS v8"] procedura. 


| 7.4.6 | 8,2 | Sì | Eseguire l'aggiornamento utilizzando le istruzioni nella link:clusters-upgrade-beegfs-v8.html["Aggiorna a BeeGFS v8"] procedura. 
|===


== Fasi di aggiornamento di BeeGFS

Nelle sezioni seguenti sono riportati i passaggi per aggiornare la raccolta BeeGFS Ansible e BeeGFS stessa. Prestare particolare attenzione a eventuali passaggi aggiuntivi per l'aggiornamento delle versioni principali o secondarie di BeeGFS.



=== Passaggio 1: Aggiornamento della raccolta BeeGFS

Per gli aggiornamenti del ritiro con accesso a. link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible Galaxy"^], eseguire il seguente comando:

[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs --upgrade
----
Per gli aggiornamenti offline della raccolta, scarica la raccolta da link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible Galaxy"^] facendo clic sul pulsante desiderato `Install Version`` e poi `Download tarball`. Trasferire il tarball al nodo di controllo Ansible ed eseguire il seguente comando.

[source, console]
----
ansible-galaxy collection install netapp_eseries-beegfs-<VERSION>.tar.gz --upgrade
----
Vedere link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html["Installazione delle raccolte"^] per ulteriori informazioni.



=== Fase 2: Aggiornare l'inventario Ansible

Apporta tutti gli aggiornamenti necessari o desiderati ai file di inventario Ansible del tuo cluster. Consulta la sezione <<Note sull'aggiornamento della versione>> qui sotto per i dettagli sui tuoi specifici requisiti di aggiornamento. Consulta la sezione link:../custom/architectures-inventory-overview.html["Panoramica di Ansible Inventory"^] per informazioni generali sulla configurazione dell'inventario HA di BeeGFS.



=== Fase 3: Aggiornamento del playbook Ansible (solo per l'aggiornamento delle versioni principali o secondarie)

Se si passa da una versione principale a una versione secondaria, nel `playbook.yml` file utilizzato per distribuire e gestire il cluster, aggiornare il nome del `beegfs_ha_<VERSION>` ruolo in modo che rifletta la versione desiderata. Ad esempio, se si desidera distribuire BeeGFS 7,4 questo sarà `beegfs_ha_7_4`:

[source, yaml]
----
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.beegfs
  tasks:
    - name: Ensure BeeGFS HA cluster is setup.
      ansible.builtin.import_role:  # import_role is required for tag availability.
        name: beegfs_ha_7_4
----
Per ulteriori dettagli sul contenuto del file del presente manuale, consulta link:../custom/architectures-deploy-ha-cluster.html["Implementare il cluster BeeGFS ha"^]la sezione.



=== Passaggio 4: Eseguire l'aggiornamento BeeGFS

Per applicare l'aggiornamento BeeGFS:

[source, console]
----
ansible-playbook -i inventory.yml beegfs_ha_playbook.yml -e "beegfs_ha_force_upgrade=true" --tags beegfs_ha
----
Dietro le quinte, il ruolo di BeeGFS ha gestirà:

* Assicurarsi che il cluster si trovi in uno stato ottimale con ciascun servizio BeeGFS situato sul nodo preferito.
* Impostare il cluster in modalità di manutenzione.
* Aggiornare i componenti del cluster ha (se necessario).
* Aggiornare ciascun nodo di file uno alla volta come segue:
+
** Metterlo in standby e eseguire il failover dei servizi sul nodo secondario.
** Aggiornare i pacchetti BeeGFS.
** Servizi di fallback.


* Spostare il cluster fuori dalla modalità di manutenzione.




== Note sull'aggiornamento della versione



=== Aggiornamento da BeeGFS versione 7.2.6 o 7.3.0



==== Modifiche all'autenticazione basata su connessione

BeeGFS versione 7.3.2 e successive richiedono che l'autenticazione basata sulla connessione sia configurata. I servizi non si avvieranno senza una delle seguenti opzioni:

* Specificando un `connAuthFile`, o
* Impostazione `connDisableAuthentication=true` nel file di configurazione del servizio.


Si consiglia vivamente di abilitare l'autenticazione basata sulla connessione per la sicurezza. Vedere link:https://doc.beegfs.io/7.3.2/advanced_topics/authentication.html#connectionbasedauth["Autenticazione basata su connessione BeeGFS"^] per ulteriori informazioni.

I `beegfs_ha*` ruoli generano e distribuiscono automaticamente il file di autenticazione a:

* Tutti i nodi file nel cluster
* Il nodo di controllo Ansible a `<playbook_directory>/files/beegfs/<beegfs_mgmt_ip_address>_connAuthFile`


Il  `beegfs_client` ruolo rileverà automaticamente e applicherà questo file ai client quando sarà presente.


WARNING: Se non hai utilizzato il  `beegfs_client` ruolo per configurare i client, devi distribuire manualmente il file di autenticazione a ciascun client e configurare l'impostazione  `connAuthFile` nel file  `beegfs-client.conf`. Quando si esegue l'aggiornamento da una versione di BeeGFS senza autenticazione basata sulla connessione, i client perderanno l'accesso a meno che non si disabiliti l'autenticazione basata sulla connessione durante l'aggiornamento impostando  `beegfs_ha_conn_auth_enabled: false` in  `group_vars/ha_cluster.yml` (scelta non consigliata).

Per ulteriori dettagli e opzioni di configurazione alternative, vedere il passaggio di configurazione dell'autenticazione della connessione nella sezione link:../custom/architectures-inventory-common-file-node-configuration.html["Specificare la configurazione del nodo file comune"^].
