---
sidebar: sidebar 
permalink: administer/clusters-failover-failback.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, failover, failback, recovery 
summary: Spostamento dei servizi BeeGFS tra nodi cluster. 
---
= Servizi di failover e failback
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Spostamento dei servizi BeeGFS tra nodi cluster.



== Panoramica

I servizi BeeGFS possono eseguire il failover tra i nodi del cluster per garantire che i client possano continuare ad accedere al file system in caso di guasto di un nodo o se è necessario eseguire una manutenzione pianificata. In questa sezione vengono descritti i vari modi in cui gli amministratori possono riparare il cluster dopo il ripristino da un errore o spostare manualmente i servizi tra i nodi.



== Fasi



=== Failover e failover



==== Failover (pianificato)

In genere, quando si deve portare un singolo nodo di file offline per la manutenzione, si desidera spostare (o svuotare) tutti i servizi BeeGFS da quel nodo. Per eseguire questa operazione, mettere il nodo in standby:

`pcs node standby <HOSTNAME>`

Dopo aver verificato l'utilizzo `pcs status` tutte le risorse sono state riavviate sul nodo di file alternativo, è possibile chiudere o apportare altre modifiche al nodo in base alle necessità.



==== Failback (dopo un failover pianificato)

Quando si è pronti a ripristinare i servizi BeeGFS sul nodo preferito, eseguire prima `pcs status` E verificare in "Node List" (elenco nodi) che lo stato sia standby. Se il nodo è stato riavviato, viene visualizzato offline fino a quando non si mettono in linea i servizi del cluster:

[source, console]
----
pcs cluster start <HOSTNAME>
----
Una volta che il nodo è online, portarlo fuori dallo standby con:

[source, console]
----
pcs cluster node unstandby <HOSTNAME>
----
Infine, ricollocare tutti i servizi BeeGFS nei nodi preferiti con:

[source, console]
----
pcs resource relocate run
----


==== Failback (dopo un failover non pianificato)

Se un nodo presenta un guasto hardware o di altro tipo, il cluster ha dovrebbe reagire automaticamente e spostare i propri servizi su un nodo integro, fornendo tempo agli amministratori per intraprendere azioni correttive. Prima di procederelink:clusters-troubleshoot.html["risoluzione dei problemi"^], fare riferimento alla sezione per determinare la causa del failover e risolvere eventuali problemi in sospeso. Una volta riacceso il nodo e funzionante, è possibile procedere con il failback.

Quando un nodo viene avviato in seguito a un riavvio non pianificato (o pianificato), i servizi cluster non vengono impostati per avviarsi automaticamente, quindi è necessario prima portare il nodo online con:

[source, console]
----
pcs cluster start <HOSTNAME>
----
Quindi, ripulire gli eventuali errori delle risorse e reimpostare la cronologia delle scherma del nodo:

[source, console]
----
pcs resource cleanup node=<HOSTNAME>
pcs stonith history cleanup <HOSTNAME>
----
Verificare in `pcs status` il nodo è online e integro. Per impostazione predefinita, i servizi BeeGFS non eseguono automaticamente il failback per evitare di spostare accidentalmente le risorse in un nodo non integro. Quando si è pronti, restituire tutte le risorse del cluster ai nodi preferiti con:

[source, console]
----
pcs resource relocate run
----


=== Spostamento di singoli servizi BeeGFS in nodi di file alternativi



==== Spostare in modo permanente un servizio BeeGFS in un nuovo nodo di file

Se si desidera modificare in modo permanente il nodo di file preferito per un singolo servizio BeeGFS, regolare l'inventario Ansible in modo che il nodo preferito venga elencato per primo ed eseguire nuovamente il playbook Ansible.

Ad esempio, in questo file di esempio `inventory.yml` , beegfs_01 è il nodo file preferito per eseguire il servizio di gestione BeeGFS:

[source, yaml]
----
        mgmt:
          hosts:
            beegfs_01:
            beegfs_02:
----
L'inversione dell'ordine causerebbe la preferenza dei servizi di gestione su beegfs_02:

[source, yaml]
----
        mgmt:
          hosts:
            beegfs_02:
            beegfs_01:
----


==== Spostare temporaneamente un servizio BeeGFS in un nodo di file alternativo

In genere, se un nodo è in fase di manutenzione, utilizzare i [passi di failover e failback] (failover e failback) per spostare tutti i servizi da quel nodo.

Se per qualche motivo è necessario spostare un singolo servizio in un nodo di file diverso, eseguire:

[source, console]
----
pcs resource move <SERVICE>-monitor <HOSTNAME>
----

WARNING: Non specificare singole risorse o il gruppo di risorse. Specificare sempre il nome del monitor per il servizio BeeGFS che si desidera trasferire. Ad esempio, per spostare il servizio di gestione BeeGFS in beegfs_02 eseguire: `pcs resource move mgmt-monitor beegfs_02`. Questo processo può essere ripetuto per spostare uno o più servizi lontano dai nodi preferiti. Verificare che l'utilizzo dei `pcs status` servizi sia stato ricollocato/avviato sul nuovo nodo.

Per spostare di nuovo un servizio BeeGFS nel nodo preferito, eliminare prima i vincoli di risorsa temporanei (ripetendo questa operazione in base alle necessità per più servizi):

[source, yaml]
----
pcs resource clear <SERVICE>-monitor
----
Quindi, quando si è pronti a spostare di nuovo i servizi sui nodi preferiti, eseguire:

[source, yaml]
----
pcs resource relocate run
----
Nota: Questo comando consente di spostare i servizi che non hanno più vincoli di risorse temporanee e che non si trovano nei nodi preferiti.
