---
sidebar: sidebar 
permalink: custom/architectures-inventory-map-services-to-file-nodes.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Specificare quali nodi di file possono eseguire ciascun servizio BeeGFS utilizzando il file inventory.yml. 
---
= Mappare i servizi BeeGFS ai nodi di file
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Specificare quali nodi di file possono eseguire ciascun servizio BeeGFS utilizzando `inventory.yml` file.



== Panoramica

In questa sezione viene illustrato come creare `inventory.yml` file. Ciò include l'elenco di tutti i nodi a blocchi e la specifica dei nodi di file che possono eseguire ciascun servizio BeeGFS.



== Fasi

Creare il file `inventory.yml` e compilarlo come segue:

. Dall'inizio del file, creare la struttura di inventario Ansible standard:
+
[source, yaml]
----
# BeeGFS HA (High_Availability) cluster inventory.
all:
  children:
----
. Creare un gruppo contenente tutti i nodi a blocchi che partecipano a questo cluster ha:
+
[source, yaml]
----
    # Ansible group representing all block nodes:
    eseries_storage_systems:
      hosts:
        <BLOCK NODE HOSTNAME>:
        <BLOCK NODE HOSTNAME>:
        # Additional block nodes as needed.
----
. Creare un gruppo che conterrà tutti i servizi BeeGFS nel cluster e i nodi di file che li eseguiranno:
+
[source, yaml]
----
    # Ansible group representing all file nodes:
    ha_cluster:
      children:
----
. Per ogni servizio BeeGFS nel cluster, definire il nodo/i file preferito/i e secondario/i che deve eseguire tale servizio:
+
[source, yaml]
----
        <SERVICE>: # Ex. "mgmt", "meta_01", or "stor_01".
          hosts:
            <FILE NODE HOSTNAME>:
            <FILE NODE HOSTNAME>:
            # Additional file nodes as needed.
----


Fare clic su link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/inventory.yml["qui"^] per un esempio di file di inventario completo.
