---
sidebar: sidebar 
permalink: custom-architectures-deploy-verify.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 'Verificare l"implementazione del file system prima di mettere il sistema in produzione.' 
---
= Verificare l'implementazione di BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verificare l'implementazione del file system prima di mettere il sistema in produzione.



== Panoramica

Prima di mettere il file system BeeGFS in produzione, eseguire alcuni controlli di verifica.



=== Fasi

. Accedere a qualsiasi client ed eseguire quanto segue per assicurarsi che tutti i nodi previsti siano presenti/raggiungibili e che non siano segnalate incoerenze o altri problemi:
+
[source, bash]
----
beegfs-fsck --checkfs
----
. Arrestare l'intero cluster, quindi riavviarlo. Da qualsiasi nodo di file eseguire quanto segue:
+
[source, bash]
----
pcs cluster stop --all # Stop the cluster on all file nodes.
pcs cluster start --all  # Start the cluster on all file nodes.
pcs status # Verify all nodes and services are started and no failures are reported (the command may need to be reran a few times to allow time for all services to start).
----
. Mettere ciascun nodo in standby e verificare che i servizi BeeGFS siano in grado di eseguire il failover su nodi secondari. Per eseguire questa operazione, accedere a uno dei nodi di file ed eseguire quanto segue:
+
[source, bash]
----
pcs status # Verify the cluster is healthy at the start.
pcs node standby <FILE NODE HOSTNAME> # Place the node under test in standby.
pcs status # Verify services are started on a secondary node and no failures are reported.
pcs node unstandby <FILE NODE HOSTNAME> # Take the node under test out of standby.
pcs status # Verify the file node is back online and no failures are reported.
pcs resource relocate run # Move all services back to their preferred nodes.
pcs status # Verify services have moved back to the preferred node.
----
. Utilizza strumenti di benchmarking delle performance come IOR e MDTest per verificare che le performance del file system soddisfino le aspettative. Esempi di test e parametri comuni utilizzati con BeeGFS sono disponibili nella link:/beegfs-design-solution-verification.html["Verifica del progetto"^] Sezione di BeeGFS su NetApp Verified Architecture.


È necessario eseguire test aggiuntivi in base ai criteri di accettazione definiti per un sito/installazione particolare.
